"""Add event_speaker association Table

Revision ID: 1c7973f738c8
Revises: e3bf06cf15a5
Create Date: 2023-09-04 21:01:42.857340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7973f738c8'
down_revision = 'e3bf06cf15a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_speaker_association',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_speaker_association')
    # ### end Alembic commands ###
