"""Add event_id to participants

Revision ID: c7a7f92ffef8
Revises: ce0c8920f021
Create Date: 2023-09-05 15:03:14.827653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a7f92ffef8'
down_revision = 'ce0c8920f021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participants', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'event_id')
    # ### end Alembic commands ###
