"""Add event_venue association Table

Revision ID: ce0c8920f021
Revises: 1c7973f738c8
Create Date: 2023-09-04 21:05:47.815958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0c8920f021'
down_revision = '1c7973f738c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_venue_association',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_venue_association')
    # ### end Alembic commands ###
