"""Create speakers table

Revision ID: f618fd2b1232
Revises: 1ea8ef8e80f6
Create Date: 2023-09-04 20:50:28.135636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f618fd2b1232'
down_revision = '1ea8ef8e80f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speakers')
    # ### end Alembic commands ###
